version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network
    command: redis-server --bind 0.0.0.0 --protected-mode no # Allow external connections
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    depends_on:
      redis:
        condition: service_healthy  # Ensures Redis is ready before starting Spring Boot
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - app_network
    volumes:
      - ./data/prices:/app/prices

networks:
  app_network:
    driver: bridge
